# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d14575efba438685445aa1fccf98b86ba540cb5a095dadccb9068c0d09d68bbc3b9731ac09070b3b5235a9ee70ed6e43fdfe9df83cc0cdd6e06cfe63e6173fb

test:
  secret_key_base: 5df33a3860919276953930c22464bb6d96b15c36d3dc77fdc700c911935d9dcf6c950203cd9ae7a302dfb70377fbdb929a01289ec81f0244e105ef4f40906bcf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
